## Module 3.1 : Numpy - Numerical Python

##### Advantages of Numpy Array.
- Allows several Mathematical operations
- Faster operations

In [1]:
import numpy as np

#### List vs Numpy - Time Taken

In [2]:
from time import process_time

##### Time taken by List:

In [7]:
from time import perf_counter

python_list = [i for i in range(10000)]

start_time = perf_counter()

python_list = [i + 5 for i in python_list]

end_time = perf_counter()

time_taken = end_time - start_time

n = 10
print(f"{time_taken:.{n}f}")


0.0003474000


In [8]:
np_array = np.array([i for i in range (10000)])
start_time = perf_counter()
np_array += 5
end_time = perf_counter()
time_taken = end_time - start_time
n = 10
print(f"{time_taken:.{n}f}")

0.0001130000


### Numpy Arrays

In [10]:
# List
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [11]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [12]:
# Creating a One dimmensional Array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [13]:
a.shape

(4,)

In [16]:
# Creating Two dimensional Array
b = np.array([(1,2,3,4), (5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [17]:
b.shape # (rows, columns)

(2, 4)

In [18]:
c = np.array([(1,2,3,4), (5,6,7,8)], dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


#### Initial Placeholders in numpy arrays

In [21]:
# Create a numpy array of Zeros 
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
# Create a numpy array of ones
x = np.ones((4,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [25]:
# Create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [29]:
# Create a numpy array with random values

b = np.random.random((3,4))
print(b)

[[0.23895398 0.43331105 0.72467973 0.42348061]
 [0.06359584 0.32630745 0.8670804  0.54958514]
 [0.93292787 0.89141502 0.8031788  0.74445959]]


In [33]:
# random integer values array within a specific range

c = np.random.randint(10, 100,(3,5)) # (start range, end range, (shape))
print(c)

[[49 50 23 95 45]
 [88 91 63 56 68]
 [76 66 84 35 72]]


In [36]:
# Array of evenly spaced values
d = np.linspace(10,30,6) # (start range, end range, number of values to be printed)
print(d)

[10. 14. 18. 22. 26. 30.]


In [40]:
#array of evenly spaced values  ---> specifying the step
e = np.arange(10,30,5) # (Start range, end range, step value)
print(e)

[10 15 20 25]


#### Convert a list/tuple to an numpy array 

In [43]:
# Convert a list to an numpy array 
list2 = [10,20,30,40,50]

np_array = np.asarray(list2)
print(np_array)

type(np_array)

[10 20 30 40 50]


numpy.ndarray

In [44]:
tuple1 = (1,2,3,4,5)

np_array = np.asarray(tuple1)
print(np_array)

type(np_array)

[1 2 3 4 5]


numpy.ndarray

#### Analysing a Numpy array

In [45]:
c = np.random.randint(10,90, (5,5))
print(c)

[[25 83 16 60 75]
 [11 19 80 60 84]
 [42 65 52 50 67]
 [32 70 47 27 66]
 [83 13 13 45 66]]


In [46]:
# Array dimension
print(c.shape)

(5, 5)


In [47]:
# Number of dimensions
print(c.ndim)


2


In [48]:
# Checking the number of elements in the array
print(c.size)

25


In [49]:
# Checking the datatype of the values in the array
print(c.dtype)

int32


#### Mathematical Operations on a Numpy array

In [51]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # Concatenates or joins the two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [54]:
# Instead of concatenating np arrays help us perform mathematical operations on these arrays
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[4 8 1]
 [0 1 6]
 [2 3 5]]
[[18 19 13]
 [16 17 12]
 [14 18 18]]


In [57]:
print(a+b)

print(a-b)

print(a*b)

print(a/b)

[[22 27 14]
 [16 18 18]
 [16 21 23]]
[[-14 -11 -12]
 [-16 -16  -6]
 [-12 -15 -13]]
[[ 72 152  13]
 [  0  17  72]
 [ 28  54  90]]
[[0.22222222 0.42105263 0.07692308]
 [0.         0.05882353 0.5       ]
 [0.14285714 0.16666667 0.27777778]]


In [59]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[22 27 14]
 [16 18 18]
 [16 21 23]]
[[-14 -11 -12]
 [-16 -16  -6]
 [-12 -15 -13]]
[[ 72 152  13]
 [  0  17  72]
 [ 28  54  90]]
[[0.22222222 0.42105263 0.07692308]
 [0.         0.05882353 0.5       ]
 [0.14285714 0.16666667 0.27777778]]


#### Array Manipulation

In [60]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 3 1]
 [9 9 0]]
(2, 3)


In [62]:
# Transpose
transpose = np.transpose(array)
print(transpose)
print(transpose.shape)

[[4 9]
 [3 9]
 [1 0]]
(3, 2)


In [63]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[2 1 0]
 [0 1 5]]
(2, 3)


In [64]:
transpose2 = array.T
print(transpose2)

[[2 0]
 [1 1]
 [0 5]]


In [65]:
# Reshaping the array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 6 7]
 [4 9 0]]
(2, 3)


In [67]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[0 6]
 [7 4]
 [9 0]]
(3, 2)
